source 'https://rubygems.org'
ruby "3.1.3"

gem 'sinatra'
gem 'eventmachine'
gem 'thin'
gem 'soap4r-ng'
gem 'rexml'
gem 'rforce'
gem 'facets'
gem 'hpricot'
gem 'json'
gem 'savon'
gem 'rack-ssl-enforcer'
gem 'rack-timeout'
gem 'httpclient'
gem 'jekyll'
gem 'jekyll-theme-minimal'